---
- name: CachyOS performance | Install settings, kernel, and headers
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: CachyOS performance
    install_pacman_packages: "{{ cachyos_performance_pacman_packages }}"

- name: CachyOS performance | Remove standard kernel and headers
  community.general.pacman:
    name: "{{ cachyos_performance_removed_pacman_packages }}"
    state: absent
