---
- name: Gaming | Create games directory
  ansible.builtin.file:
    path: "{{ user_home }}/Games"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Gaming | Install packages
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: Gaming
    install_pacman_packages: "{{ gaming_pacman_packages }}"
    install_aur_packages: "{{ gaming_aur_packages }}"

- name: Gaming | Configure Sunshine credentials
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command:
    argv:
      - sunshine
      - --creds
      - "{{ sunshine_username }}"
      - "{{ sunshine_password }}"
  environment:
    HOME: "{{ user_home }}"
  changed_when: false
  no_log: true
  when: inventory_hostname == "desktop"

- name: Gaming | Enable Sunshine user service globally
  ansible.builtin.systemd_service:
    name: app-dev.lizardbyte.app.Sunshine.service
    enabled: true
    scope: global
  when: inventory_hostname == "desktop"
