[ids]
*
m:1b1c:1bac

# General keyboard and numpad actions
[main]
capslock = noop
numlock = togglem(numpad, numlock)
kpenter = command(runuser -u charl -- /home/charl/.local/bin/find-phone.py)
kpplus = brightnessup
kpminus = brightnessdown
scrolllock = C-delete

# Actions available when Num Lock enables the numpad layer
[numpad]
kp4 = command(runuser -u charl -- /home/charl/.local/bin/fan-toggle.py)
