---
- name: Downloader | Create HexChat configuration directory
  ansible.builtin.file:
    path: "{{ downloader_hexchat_config_dir }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Downloader | Configure HexChat network list
  ansible.builtin.copy:
    src: hexchat/servlist.conf
    dest: "{{ downloader_hexchat_servlist_path }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"

- name: Downloader | Configure HexChat colors
  ansible.builtin.copy:
    src: hexchat/colors.conf
    dest: "{{ downloader_hexchat_colors_path }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"

- name: Downloader | Configure HexChat preferences
  ansible.builtin.lineinfile:
    path: "{{ downloader_hexchat_conf_path }}"
    regexp: "^{{ item.key }} ="
    line: "{{ item.key }} = {{ item.value }}"
    create: true
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"
  loop:
    - key: dcc_auto_recv
      value: "2"
    - key: dcc_completed_dir
      value: "{{ downloader_hexchat_complete_directory }}"
    - key: dcc_dir
      value: "{{ downloader_hexchat_incomplete_directory }}"
    - key: gui_autoopen_recv
      value: "0"
    - key: gui_autoopen_send
      value: "0"
    - key: gui_slist_skip
      value: "1"
  loop_control:
    label: "{{ item.key }}"
