---
- name: KDE | Configure Spectacle to copy screenshots to the clipboard
  community.general.kdeconfig:
    path: "{{ user_home }}/.config/spectaclerc"
    values:
      - group: General
        key: clipboardGroup
        value: PostScreenshotCopyImage
      - group: General
        key: defaultSaveLocation
        value: "file://{{ user_home }}/Pictures/Screenshots"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
