---
- name: KDE | Configure Spectacle to copy screenshots to the clipboard
  community.general.kdeconfig:
    path: "{{ user_home }}/.config/spectaclerc"
    values:
      - group: General
        key: clipboardGroup
        value: PostScreenshotCopyImage
      - group: ImageSave
        key: imageSaveLocation
        value: "file://{{ user_home }}/Pictures/Screenshots"
      - group: VideoSave
        key: translatedScreencastsFolder
        value: Screencasts
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
