[ids]
*

[main]
capslock = noop
scrolllock = C-delete

[meta]
p = command(runuser -u charl -- /home/charl/.local/bin/fan-toggle.py)

1 = M-mute
2 = M-volumedown
3 = M-volumeup
4 = M-micmute

mute = M-1
volumedown = M-2
volumeup = M-3
micmute = M-4

[meta+shift]
1 = M-S-mute
2 = M-S-volumedown
3 = M-S-volumeup
4 = M-S-micmute

mute = M-S-1
volumedown = M-S-2
volumeup = M-S-3
micmute = M-S-4
