[ids]
*

[main]
capslock = noop
micmute = command(runuser -u charl -- /home/charl/.local/bin/fan-toggle.py)
scrolllock = C-delete

[meta]
1 = M-mute
2 = M-volumedown
3 = M-volumeup
4 = M-f4
mute = M-1
volumedown = M-2
volumeup = M-3
f4 = M-4
