[ids]
*

# General keyboard actions
[main]
capslock = noop
scrolllock = C-delete

# Super shortcut
[meta]
p = command(runuser -u charl -- /home/charl/.local/bin/fan-toggle.py)

# Emit extended function keys for Spotify shortcuts
[shift]
mute = f14
volumedown = f15
volumeup = f16
micmute = f17
