---
downloader_pacman_packages:
  # BitTorrent client
  - qbittorrent
  # Media downloader
  - yt-dlp

downloader_aur_packages:
  # Download manager
  - jdownloader2
  - hexchat

# Directory
downloader_qbittorrent_complete_directory: "{{ user_home }}/Torrents/qBittorrent/Complete"
downloader_qbittorrent_incomplete_directory: "{{ user_home }}/Torrents/qBittorrent/Incomplete"
downloader_jdownloader_directory: "{{ user_home }}/Torrents/JDownloader"
downloader_hexchat_directory: "{{ user_home }}/Torrents/HexChat"
downloader_hexchat_complete_directory: "{{ downloader_hexchat_directory }}/Complete"
downloader_hexchat_incomplete_directory: "{{ downloader_hexchat_directory }}/Incomplete"

# Config
downloader_jdownloader_config_path: "{{ user_home }}/.jd/cfg/org.jdownloader.settings.GeneralSettings.json"
downloader_qbittorrent_config_path: "{{ user_home }}/.config/qBittorrent/qBittorrent.conf"
downloader_hexchat_config_dir: "{{ user_home }}/.config/hexchat"
downloader_hexchat_conf_path: "{{ downloader_hexchat_config_dir }}/hexchat.conf"
downloader_hexchat_colors_path: "{{ downloader_hexchat_config_dir }}/colors.conf"
downloader_hexchat_servlist_path: "{{ downloader_hexchat_config_dir }}/servlist.conf"
