---
kde_pacman_packages:
  - ark
  - kitty
  - kvantum
  - discover
  - dolphin
  - kio-extras
  - kcalc
  - kdeconnect
  - ffmpegthumbs

  # Icon theme
  - papirus-icon-theme

  # dependency: community.general.kdeconfig (provides kwriteconfig6)
  - kconfig

kde_aur_packages:
  # Theme
  - klassy
  # Wallpaper
  - plasma6-wallpapers-smart-video-wallpaper-reborn

# Input
kde_cursor_launch_feedback_enabled: false
kde_shake_cursor_enabled: false
kde_keyboard_layout: us_programmer
kde_keyboard_display_name: us_programmer

# Workspaces
kde_workspace_count: 4

# Notifications
kde_status_osd_enabled: false
kde_volume_step: 10
kde_audio_feedback_enabled: false
kde_system_sounds_enabled: false
kde_system_bell_enabled: false

# Applications
kde_terminal_command: kitty
kde_terminal_desktop: kitty.desktop

# Dolphin
kde_dolphin_places_file: "{{ user_home }}/.local/share/user-places.xbel"
kde_server_smb: "smb://192.168.2.36/"

kde_dolphin_places:
  - title: Applications
    href: "file://{{ user_home }}/Applications"
    icon: folder
  - title: Games
    href: "file://{{ user_home }}/Games"
    icon: folder
  - title: Projects
    href: "file://{{ user_home }}/Projects"
    icon: folder
  - title: Torrents
    href: "file://{{ user_home }}/Torrents"
    icon: folder-downloads
  - title: Server
    href: "{{ kde_server_smb }}"
    icon: network-server
