---
- name: Update system
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Update | Run topgrade
      ansible.builtin.command:
        cmd: topgrade --yes --no-ask-retry
      become_user: "{{ user_name }}"
      environment:
        HOME: "{{ user_home }}"
      changed_when: true
      failed_when: false
