---
syncthing_pacman_packages:
  - syncthing
  - python-lxml

syncthing_devices: []

syncthing_folders:
  - id: pictures
    label: Pictures
    path: "{{ user_home }}/Pictures"
  - id: documents
    label: Documents
    path: "{{ user_home }}/Documents"
