---
- name: Bin | Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: "{{ bin_dest }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Bin | Install scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ bin_dest }}/{{ item | basename }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
  loop: "{{ query('ansible.builtin.fileglob', role_path ~ '/files/*') }}"

- name: Bin | Ensure ~/.config/homectl exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/homectl"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Bin | Deploy homectl configuration
  ansible.builtin.template:
    src: homectl-config.yml.j2
    dest: "{{ user_home }}/.config/homectl/config.yml"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"
  no_log: true
