---
- name: Media | Install packages
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: Media
    install_pacman_packages: "{{ media_pacman_packages }}"
    install_aur_packages: "{{ media_aur_packages }}"
