---
virtualization_pacman_packages:
  # Hypervisor
  - qemu-desktop
  - libvirt

  # Applications
  - virt-manager

  # Firmware
  - edk2-ovmf

  # Network
  - dnsmasq

  # Dependency
  - python-lxml
  - libvirt-python
