---
- name: Communication | Install packages
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: Communication
    install_pacman_packages: "{{ communication_pacman_packages }}"

- name: Communication | Configure Thunderbird
  ansible.builtin.include_tasks: thunderbird.yml
