---
# Paths
mihon_desktop_dest: "{{ user_home }}/.local/share/applications/mihon.desktop"
mihon_icon_dest: "{{ user_home }}/.local/share/icons/mihon.png"
mihon_icon_src: mihon.png

# Browser
mihon_url: "https://mihon.org"
mihon_browser: "brave-origin"
mihon_wm_class: "brave-mihon.org__-Default"
