---
- name: Emulation | Create ROMs directory
  ansible.builtin.file:
    path: "{{ user_home }}/Games/ROMs"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Emulation | Install packages
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: Emulation
    install_aur_packages: "{{ emulation_aur_packages }}"
