[ids]
*

[main]
capslock = noop
micmute = command(runuser -u charl -- /home/charl/.local/bin/fan-toggle.py)
kp4 = command(runuser -u charl -- /home/charl/.local/bin/fan-toggle.py)
kpenter = command(runuser -u charl -- /home/charl/.local/bin/find-phone.py)
scrolllock = C-delete

[shift]
scrolllock = A-delete

[alt]
scrolllock = S-A-delete
