[ids]
*

[main]
capslock = noop
numlock = togglem(numpad, numlock)
micmute = command(runuser -u charl -- /home/charl/.local/bin/fan-toggle.py)
kpenter = command(runuser -u charl -- /home/charl/.local/bin/find-phone.py)
scrolllock = C-delete

[numpad]
kp4 = command(runuser -u charl -- /home/charl/.local/bin/fan-toggle.py)
